name: dnd
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  badges: ^3.1.1
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.5
  get_it: ^7.2.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/main_screen_assets/icons/bottom_icons/
    - assets/main_screen_assets/icons/bottom_icons_active/
    - assets/main_screen_assets/icons/dice/
    - assets/main_screen_assets/icons/spells/
    - assets/menu_screen_assets/background/
